# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost:7208
@contentType = application/json
@token = token
@refresh = token

### home (anonymous)
GET {{host}}/
Authorization: Bearer {{token}}

### authenticated user
GET {{host}}/user
Authorization: Bearer {{token}}

### authenticated admin
GET {{host}}/admin
Authorization: Bearer {{token}}

### authenticated refresh
GET {{host}}/refresh
Authorization: Bearer {{refresh}}
