# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost:7208
@contentType = application/json
@token = token

### Create ShortenedUrl
POST {{host}}/api/v1/short-url
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "longUrl" : "https://darthpedro.net/blazor-how-to-articles/",
    "summary" : "DarthPedro's Blazor blog series"
}

### Create ShortenedUrl - future publish
POST {{host}}/api/v1/short-url
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "longUrl" : "https://darthpedro.net/blazor-how-to-articles-future/",
    "summary" : "DarthPedro's Blazor blog series future",
    "publishOn": "2024-10-04T18:44:51.5859981"
}

### Get ShortUrl by code
GET {{host}}/ajLmSGyX

### Get ShortUrls by owner
GET {{host}}/api/v1/short-url/
Authorization: Bearer {{token}}

### Get ShortUrl by id
GET {{host}}/api/v1/short-url/9d09f2d6-9205-49c8-a685-cda3629d6100
Authorization: Bearer {{token}}

### Update ShortenedUrl
PUT {{host}}/api/v1/short-url/9d09f2d6-9205-49c8-a685-cda3629d6100
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "longUrl" : "https://darthpedro.net/blazor-how-to-articles222/",
    "summary" : "DarthPedro's Blazor blog series222"
}

### Publish ShortenedUrl
PUT {{host}}/api/v1/short-url/9d09f2d6-9205-49c8-a685-cda3629d6100/publish
Authorization: Bearer {{token}}

### Unpublish ShortenedUrl
PUT {{host}}/api/v1/short-url/9d09f2d6-9205-49c8-a685-cda3629d6100/unpublish
Authorization: Bearer {{token}}

### Delete ShortUrl
DELETE {{host}}/api/v1/short-url/003d9df9-600b-4b01-befe-e855251e1724
Authorization: Bearer {{token}}
