# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost:7208
@contentType = application/json
@token = token

### Create ShortenedUrl
POST {{host}}/api/v1/short-url
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "longUrl" : "https://darthpedro.net/blazor-how-to-articles/",
    "summary" : "DarthPedro's Blazor blog series"
}

### Get ShortUrl by code
GET {{host}}/L4qvKm8D

### Get ShortUrl by id
GET {{host}}/api/v1/short-url/9748ef51-ef45-43e5-90c0-1609f7a007e2
Authorization: Bearer {{token}}
